packages:
  - backend
  - frontend
  - noble-bridge
allowBuilds:
  '@abandonware/noble': true
  '@prisma/client': true
  '@prisma/engines': true
  esbuild: true
  prisma: true
  usocket: true
patchedDependencies:
  dbus-next@0.10.2: patches/dbus-next@0.10.2.patch
